# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APPSTUD-Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage'
  pod 'AlamofireObjectMapper'
  pod 'RealmSwift'
 
  # Pods for APPSTUD-Test

  target 'APPSTUD-TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APPSTUD-TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
